<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Arranged Dinner' => 'Cenas concertadas',
    'Baby sitter' => 'Niñera',
    'Chauffeur' => 'Chófer',
    'Code' => 'Código',
    'Cooker' => 'Cocinero',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Delete' => 'Eliminar',
    'Descriptions' => 'Descripciones',
    'Events' => 'Eventos',
    'Excursions' => 'Excursiones',
    'Files' => 'Ficheros',
    'Home' => 'Inicio',
    'ID' => 'ID',
    'Is Featured' => 'Destacado',
    'Is For Rent' => 'En alquiler',
    'Language Code' => 'Código de Idioma',
    'Md Content' => 'Contenido Md',
    'Name' => 'Nombre',
    'Offer ID' => 'ID Oferta',
    'Offers' => 'Ofertas',
    'Our Reference' => 'Nuestra Referencia',
    'Personal Shopper' => 'Asistente de Compras',
    'Rentals' => 'Alquileres',
    'Reset' => 'Reiniciar',
    'Sales' => 'Ventas',
    'Search' => 'Buscar',
    'Security' => 'Seguridad',
    'Their Reference' => 'Su Referencia',
    'Title' => 'Título',
    'Titles' => 'Títulos',
    'Touristic Guide' => 'Guía Turístico',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Url' => 'Url',
    'VIP Services' => 'Servicios VIP',
    'Vacations' => 'Vacaciones',
    'Valid From' => 'Válido Desde',
    'Valid Until' => 'Válido Hasta',
];
