<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About us' => 'Sobre nosotros',
    'Activities' => 'Actividades',
    'Activity ID' => 'ID Actividad',
    'Activity details' => 'Detalles de la actividad',
    'Add Pictures' => 'Añadir imágenes',
    'Alternative activities in the Canary Islands: speleo, hiking, canyoing, sports, expositions, skydiving, partying, etc.' => 'Actividades alternativas en las Islas Canarias: espeleo, senderismo, barranquismo, deportes, exposiciones, paracaidismo, fiestas, etc.',
    'Are you sure you want to delete this item?' => '¿Está seguro que desea eliminar este elemento?',
    'Author' => 'Autor',
    'Blog' => 'Blog',
    'Blog entries' => 'Entradas del blog',
    'Browse …' => 'Navegar …',
    'By' => 'Por',
    'Calendar' => 'Calendario',
    'Capacity' => 'Capacidad',
    'Know our history' => 'Conoce nuestra historia',
    'Contact form' => 'Formulario de contacto',
    'Contact us at' => 'Contactanos en',
    'Description' => 'Descripción',
    'Did you like this post? Please share it with your followers!' => '¿Te ha gustado esta entrada? Por favor, ¡compártela con tus seguidores!',
    'Discover corners of Gran Canaria' => 'Descubre rincones de Gran Canaria',
    'Details' => 'Detalles',
    'Download catalog' => 'Descargar el catálogo',
    'Be carried away by the flavors' => 'Déjate llevar por los sabores',
    'End Place Map URL' => 'URL de llegada en mapa',
    'End Place Name' => 'Lugar de llegada',
    'End Timestamp' => 'Fecha y hora de llegada',
    'Enroll me!' => '¡Apuntarme!',
    'Explore the interior of the island and discover small natural monuments, enjoy unique places, connect with nature and live a day of adventure with our experiences. Discover other ways to live our coast with our water activities.' => 'Explora el interior de la isla y podrás descubrir pequeños monumentos naturales, disfrutar de parajes únicos, conectar con la naturaleza y vivir un día de aventuras con nuestras experiencias. Descubre otras formas de vivir nuestra costa con nuestras actividades acuáticas.',
    'From' => 'Desde',
    'Get submerged in our intense flavors, enjoy an island full of aromas and colors. Try our <em>papas arrugás</em> with <em>mojo picón</em>, taste our cheeses and wines, savor the <em>gofio</em> in its diverse culinary creations. Take a good taste of Gran Canaria.' => 'Sumergente en nuestros intensos sabores, disfruta de una isla llena de aromas y colores. Prueba nuestras <em>papas arrugás</em> con <em>mojo picón</em>, cata nuestros quesos y vinos, saborea el gofio en las diversas creaciones culinarias. Llévate un buen sabor de boca de Gran Canaria.',
    'Group offers and prices' => 'Ofertas y precios de grupo',
    'Includes' => 'Incluye',
    'Itinerary' => 'Itinerario',
    'Join us and live an unforgettable experience' => 'Únete a nosotros y vive una experiencia inolvidable',
    'Lead Paragraph' => 'Párrafo introductorio',
    'Live new experiences' => 'Vive nuevas experiencias',
    'Loading...' => 'Cargando...',
    'Login' => 'Login',
    'Menu' => 'Menú',
    'More Info' => 'Más información',
    'More activities' => 'Más actividades',
    'Notes' => 'Notas',
    'Orders and refunds' => 'Pedidos y devoluciones',
    'Pictures' => 'Imágenes',
    'Please fill out the following fields to login:' => 'Por favor, rellene los siguientes campos para iniciar sesión:',
    'Post Date' => 'Fecha del Post',
    'Price' => 'Precio',
    'Price Eucents' => 'Precio en cénts. de Euro',
    'Privacy policy' => 'Política de privacidad',
    'Published on' => 'Publicado el',
    'Return' => 'Llegada',
    'Slug' => 'Slug',
    'Start' => 'Salida',
    'Start Place Map URL' => 'URL de salida en mapa',
    'Start Place Name' => 'Lugar de salida',
    'Start Timestamp' => 'Fecha y hora de salida',
    'Subtitle' => 'Subtítulo',
    'Subtitles' => 'Subtítulos',
    'Travel through time and know the history of the Canaries, how the islands were formed, how the Aborigines lived and the different periods after the conquest. Visit the neighborhood of Vegueta and listen to what its cobbled streets tell you about Columbus or his stories of pirates.' => 'Viaja a través del tiempo y conoce la historia de Canarias, cómo se formaron las islas, cómo vivían los aborígenes y los diferentes períodos tras las conquista. Visita el barrio de Vegueta y escucha lo que sus empedradas calles te cuentan sobre Colón o sus historias de piratas.',
    'Upcoming activities' => 'Próximas actividades',
    'Upcoming activity' => 'Próxima actividad',
    'Update {modelClass}' => 'Actualizar {modelClass}',
    'Upload' => 'Subir',
    'Vacants' => 'Vacantes',
    'of' => 'de',
    '{n} files selected' => '{n} ficheros seleccionados',
    'Code' => 'Código',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Delete' => 'Eliminar',
    'Descriptions' => 'Descripciones',
    'Files' => 'Ficheros',
    'Home' => 'Inicio',
    'ID' => 'ID',
    'Language Code' => 'Código de Idioma',
    'Md Content' => 'Contenido Md',
    'Name' => 'Nombre',
    'Title' => 'Título',
    'Titles' => 'Títulos',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Url' => 'Url',
];
