<div class="container">
<h1 class="page-header text-center">Aviso legal</h1>

<h2>Objeto</h2>
<p>El objeto de las presentes condiciones generales es regular el uso que pueden realizar los usuarios de la web corporativa de Canary Gay Experience , que actualmente se encuentra en la URL: www.canarygayexperience.com (en adelante la web corporativa).</p>
<p>Canary Gay Experience es una compañía española con domicilio social en Calle Bonsai s/n (C.P. 35100) San Bartolomé de Tirajana – Las Palmas de Gran Canaria.</p>

<h2>Funcionamiento de la web corporativa</h2>
<p>Canary Gay Experience se reserva la facultad de efectuar, en cualquier momento y sin necesidad de previo aviso, las modificaciones y actualizaciones que estime convenientes en la web corporativa, de la configuración y presentación de ésta y de las condiciones de acceso pudiendo incluir servicios y contenidos adicionales a los actuales o, en su caso, suprimirlos o modificar la configuración y presentación de ésta y de las condiciones de acceso.</p>
<p>Canary Gay Experience podrá bloquear el acceso a todos o parte de los usuarios de la misma para proceder a realizar las modificaciones o reparaciones que considere necesarias en cualquier momento. En ningún caso, Canary Gay Experience será responsable del inadecuado funcionamiento del sistema si ello obedece a una defectuosa configuración de los equipos del usuario o a su insuficiente capacidad para soportar los sistemas informáticos indispensables para poder hacer uso del servicio.</p>
<p>Canary Gay Experience se compromete a realizar todos sus esfuerzos para mantener actualizada la información y contenidos que introduzca en la web corporativa, si bien el usuario conoce que pueden existir incorrecciones en los contenidos y servicios incluidos en la web corporativa que, en su caso, Canary Gay Experience procederá a subsanar a la máxima brevedad en cuanto tenga conocimiento de su existencia. En cualquier caso, Canary Gay Experience no garantiza la inexistencia de interrupciones o errores en el acceso a la web corporativa, en su contenido, ni que éste se encuentre actualizado, aunque desarrollará sus mejores esfuerzos para, en su caso, evitarlos, subsanarlos o actualizarlos.</p>
<p>Canary Gay Experience no se hace responsable de los posibles errores de seguridad que se puedan producir ni de los posibles daños que puedan causarse al sistema informático del usuario (hardware y software), los ficheros o documentos almacenados en el mismo, como consecuencia de la presencia de virus en el ordenador del usuario utilizado para la conexión a los servicios y contenidos en la web.</p>
<p>Canary Gay Experience no asume responsabilidad alguna derivada de la concesión o contenidos de los enlaces de terceros a los que se hace referencia en la web, ni garantiza la ausencia de virus u otros elementos en los mismos que puedan producir alteraciones en el sistema informático (hardware y software), los documentos o los ficheros del usuario, excluyendo cualquier responsabilidad por los daños de cualquier clase causados al usuario por este motivo.</p>

<h2>Propiedad intelectual e industrial</h2>
<p>Los derechos de propiedad intelectual de la web www.canarygayexperience.com, la información, datos, contenidos, bases de datos, diseños, fotografías, códigos fuente, estructuras de navegación y demás servicios o productos telemáticos integrados en la web corporativa a los que Canary Gay Experience permite tener acceso, así como la de los productos eventualmente derivados y los manuales de utilización son propiedad exclusiva de Canary Gay Experience, de sus proveedores, o de los titulares respectivos según proceda, por lo que el usuario se compromete a no infringir ningún derecho derivado de la propiedad industrial o intelectual. El usuario se compromete a utilizar dicha información y servicios exclusivamente para sus propias necesidades y a no realizar directa o indirectamente una explotación comercial de los servicios a los que tiene acceso o de los resultados obtenidos gracias a la utilización de la web corporativa, salvo que haya obtenido consentimiento expreso de Canary Gay Experience.</p>

<h2>Autenticación</h2>
<p>Canary Gay Experience podrá establecer diferentes sistemas de autenticación en la web corporativa de tal forma que a través de datos solicitados previamente o a través de identificadores y contraseñas se autentique a los usuarios de la web corporativa. En caso de que Canary Gay Experience realice la autenticación de los usuarios a través de identificadores y contraseñas, tanto el identificador como la contraseña pertenecerán exclusivamente a la persona a la que se le conceden. El usuario deberá mantener bajo su exclusiva responsabilidad tanto el identificador como la contraseña en la más estricta y absoluta confidencialidad, asumiendo, por tanto, cuantos daños o consecuencias de todo tipo se deriven del quebrantamiento o revelación del secreto.</p>

<h2>Ética y responsabilidad derivada del uso por el usuario de internet y de la web corporativa</h2>
<p>Canary Gay Experience no será en ningún caso responsable del uso de la web corporativa que realice el usuario. El usuario se abstendrá de llevar a cabo cualquier conducta en el uso de la web corporativa o de los recursos puestos a su disposición que atente contra los derechos de propiedad intelectual o industrial de Canary Gay Experience o de terceros, que vulnere o transgreda el honor, la intimidad personal o familiar o la imagen a terceros, o que sean ilícitos o atenten a la moralidad y dejará en todo caso indemne a Canary Gay Experience frente cualquier reclamación, judicial o extrajudicial, que se presente frente a ella como consecuencia de dicho uso.</p>
<p>El usuario se abstendrá de llevar a cabo por cualquier medio cualquier destrucción, alteración, inutilización o daños de los datos, programas o documentos electrónicos pertenecientes a Canary Gay Experience, a sus proveedores o a terceros, así como de introducción o difundir en la Red programas, virus, applets, o cualquier instrumento físico o electrónico que causen o sean susceptibles de causar cualquier tipo de alteración en la Red, en el sistema, o en los equipos de terceros.</p>
<p>Queda expresamente prohibido borrar, modificar los mensajes de correo electrónico de otros usuarios, enviar mensajes de correo masivo, con fines comerciales o publicitarios, así como llevar a cabo cualquier tipo de actividad o práctica que transgreda los principios de buena conducta aceptados generalmente entre los usuarios de Internet.</p>

<h2>Uso de las cookies</h2>
<p>Las cookies son pequeños dispositivos que permiten recordar datos de navegación de los usuarios, las cookies utilizadas por Canary Gay Experience no proporcionan datos personales de los usuarios, ni pueden asociarse a persona identificada o identificable.</p>
<p>Canary Gay Experience utiliza cookies para recordar las preferencias de los usuarios en sus visitas a la página o sitios web de Canary Gay Experience y las utiliza para hacer una navegación más eficiente para el usuario en próximas visitas.</p>
<p>El usuario puede desactivar de su ordenador la instalación de cookies mediante la configuración de su navegador. Para desactivar correctamente las cookies le recomendamos consultar directamente el manual de su navegador ya que, dependiendo de éste, la forma de hacerlo puede variar.</p>

<h2>Reclamaciones</h2>
<p>El usuario podrá dirigir las reclamaciones sobre los servicios prestados a Canary Gay Experience, Calle Bonsai s/n (C.P. 35100) San Bartolomé de Tirajana – Las Palmas de Gran Canaria. Telf.: 699 798 809.</p>
<p>El usuario tendrá disponibles Hojas de Reclamaciones Oficiales en la dirección anteriormente referida. Canary Gay Experience y el usuario, con renuncia expresa a cualquier otro fuero, se someten al de los Juzgados y Tribunales de Las Palmas de Gran Canaria</p>
</div>
