<div class="container">
<h1 class="page-header text-center">Política de privacidad</h1>
<p>Canary Gay Experience garantiza la privacidad de los datos de carácter personal aportados según la LOPD.</p>
<p>La visita a este website no supone que el usuario esté obligado a facilitar ninguna información sobre sí mismo, no obstante durante la visita es posible que se soliciten datos de carácter personal a través de formularios. Dichos datos serán utilizados para contestar la solicitud por su parte realizada y para el envío de la misma, también serán utilizados para enviarles información de nuestra empresa y servicios por cualquier medio de comunicación. Al enviarnos dicho formulario usted está aceptado explícitamente la recepción de los mismos, en el caso que no deseara recibir nuestra información, únicamente tendría que enviar un correo electrónico solicitando la baja de nuestro servicio informativo a <a mailto="direccion@canarygayexperience.com">direccion@canarygayexperience.com</a></p>
<p>Sus datos personales formarán parte del fichero clientes, cuyo destinatario y responsable del almacenamiento y del tratamiento del mismo es: ANTONIO MIGUEL SUÁREZ RODRIGUEZ, en Calle Bonsai s/n, 35100 de San Bartolomé de Tirajana – Las Palmas de Gran Canaria, donde podrá ejercer los derechos de acceso, rectificación, cancelación y oposición, mediante escrito la dirección antes indicada incluyendo copia del DNI o documento identificativo equivalente.</p>
<p>La negativa a proporcionar los datos supondrá la no prestación o la imposibilidad de acceder al servicio para los que eran solicitados. Usted tiene derecho a recibir respuesta de cualquier pregunta, consulta o aclaración que le surja derivada de este formulario.</p>
<p>En el supuesto de que aporte sus datos a través de un mensaje de correo electrónico, éstos formarán parte del mismo fichero cuya finalidad será la gestión de la solicitud o comentario que nos realiza, siendo aplicables el resto de extremos indicados en el párrafo anterior.</p>
<p>Todos sus datos serán dados de baja definitivamente de nuestra base de datos por los siguientes motivos: 1) a petición suya, 2) cuándo hayan dejado de ser necesarios para los fines que motivaron su recogida.</p>
<p>Las partes se someten, a su elección, para la resolución de los conflictos y con renuncia a cualquier otro fuero, a los juzgados y tribunales del domicilio del propietario del sitio Web.</p>
</div>
